// DO NOT MODIFY
// This file is autogenerated
// To update: run "yarn gql:codegen-operations"

/* eslint-disable */


      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {
    "ActivityUnion": [
      "ListActivity",
      "MessageActivity",
      "TextActivity"
    ],
    "LikeableUnion": [
      "ActivityReply",
      "ListActivity",
      "MessageActivity",
      "TextActivity",
      "Thread",
      "ThreadComment"
    ],
    "NotificationUnion": [
      "ActivityLikeNotification",
      "ActivityMentionNotification",
      "ActivityMessageNotification",
      "ActivityReplyLikeNotification",
      "ActivityReplyNotification",
      "ActivityReplySubscribedNotification",
      "AiringNotification",
      "FollowingNotification",
      "MediaDataChangeNotification",
      "MediaDeletionNotification",
      "MediaMergeNotification",
      "RelatedMediaAdditionNotification",
      "ThreadCommentLikeNotification",
      "ThreadCommentMentionNotification",
      "ThreadCommentReplyNotification",
      "ThreadCommentSubscribedNotification",
      "ThreadLikeNotification"
    ]
  }
};
      export default result;
    